### ISSUE TITLE
Add support for axis positioning dialog

### ISSUE THREAD

**Issue by mfs12** [Duet3D/PanelDueFirmware#158] opened 2021-07-26 10:52 UTC
Currently only z-axis is support. Add support for all other possible axis, .i.e. X and Y.

**Comment by mfs12** [comment] 2021-07-26 10:54
Check https://github.com/mfs12/endocrine/blob/config-m291-test/macros/test-m291-xyz.g for test macro.

**Comment by dc42** [comment] 2021-08-04 12:00
Duplicate of #102.

**Closed by dc42** 2021-08-04 12:00 UTC
Labels: feature
