### ISSUE TITLE
PanelDue 3.2.8 Issues

### ISSUE THREAD

**Issue by dang472** [Duet3D/PanelDueFirmware#92] opened 2021-01-19 01:16 UTC
1) Tool icon blinks red for no reason when no tools selected
2) Even though part fan is 100% in web interface. The paneldue shows 0.

**Comment by wilriker** [comment] 2021-01-19 08:12
Hi @dang472 part 1 is already fixed in 3.2.9.
Re fan: PanelDueFirmware shows the fan speed of the currently selected tool. If there is no tool selected it will not show fan speed. But I will change that in the next version to default to fan 0 then.

**Closed** 2021-01-19 08:18 UTC

**Comment by dang472** [comment] 2021-01-19 13:34
Hi, For part 2. The printer was printing with a tool selected and still had the fan speed at 0. I have the default fan 0 mapped to all my tools. I installed 3.2.9 and I noticed part 1 was fixed. 
-------- Original message --------From: Manuel <notifications@github.com> Date: 2021-01-19  3:18 a.m.  (GMT-05:00) To: Duet3D/PanelDueFirmware <PanelDueFirmware@noreply.github.com> Cc: dang472 <giri@ieee.org>, Mention <mention@noreply.github.com> Subject: Re: [Duet3D/PanelDueFirmware] PanelDue 3.2.8 Issues (#92) 
Hi @dang472 part 1 is already fixed in 3.2.9.
Re fan: PanelDueFirmware shows the fan speed of the currently selected tool. If there is no tool selected it will not show fan speed. But I will change that in the next version to default to fan 0 then.

**Comment by wilriker** [comment] 2021-01-19 13:54
I just tried and I cannot reproduce the issue with the fan not showing the correct value if a tool is selected (if none is selected it will show the initial or previous tool's value - which might be zero).

Please test again and if the problem persists provide your `config.g` as well as the output of
```
M409 K"fans" F"d99v"
M409 K"tools" F"d99v"
```

**Comment by dang472** [comment] 2021-01-19 17:49
When I installed 3.2.9 it seems to be fixed. If it manifests again I will let you know. While printing the sliced gcode file increased the fan speed. The web interface was correct. But the paneldue showed zero. 
-------- Original message --------From: Manuel <notifications@github.com> Date: 2021-01-19  9:04 a.m.  (GMT-05:00) To: Duet3D/PanelDueFirmware <PanelDueFirmware@noreply.github.com> Cc: dang472 <giri@ieee.org>, Mention <mention@noreply.github.com> Subject: Re: [Duet3D/PanelDueFirmware] PanelDue 3.2.8 Issues (#92) 
I just tried and I cannot reproduce the issue with the fan not showing the correct value if a tool is selected (if none is selected it will show the initial or previous tool's value - which might be zero).
Please test again and if the problem persists provide your config.g as well as the output of
M409 K"fans" F"d99v"
M409 K"tools" F"d99v"
