### ISSUE TITLE
Small Color issue!

### ISSUE THREAD

**Issue by JPluess** [Duet3D/PanelDueFirmware#88] opened 2021-01-08 14:43 UTC
Hi there,
when I connect only Duet2Wifi v1.04 with PanelDue v3. (no sensors connected)
I get this strange look.
Thanks.

![0747fc42-38e1-4199-9342-36e712220e13](https://user-images.githubusercontent.com/7995240/104027600-e6f3a100-51c7-11eb-8c5f-9c30aec5ae29.jpg)

**Comment by wilriker** [comment] 2021-01-08 15:00
This usually is a result of flashing the wrong version (display drivers differ slightly between the various versions). Can you please state
* PanelDue hardware version
* PanelDueFirmware version flashed

**Comment by JPluess** [comment] 2021-01-08 16:17
Hi there, 
Firmware are the latest stable. 3.2.7. before i had 3.2.6 with the same issue.
it's is only with the light theme heatbed button, dark 1 and dark 2 seem to be ok. 
i installed PanelDueFirmware-v3-5.0-nologo.zip!

**Comment by dc42** [comment] 2021-01-08 18:08
You haven't told us what PanelDue hardware you have. If it is a PanelDue 5i then you have flashed the wrong firmware binary.

**Comment by JPluess** [comment] 2021-01-08 19:14
Dear, 
thanks, it was the correct binary. :) i have now flashed the wrong file 5i, and now the colors are different, instead of red its blue! But the issue with the heatbead having 2 colors remains.   

![1c512db3-7d09-4e4b-8d7b-51b0f4d96ae5](https://user-images.githubusercontent.com/7995240/104054845-1fa67100-51ee-11eb-94b3-e255fd7e950b.jpeg)

**Comment by JPluess** [comment] 2021-01-08 19:25
Nice! I can provide a video!
when loading, it first does the correct beige color. 
Than it overlays green and purple!

https://user-images.githubusercontent.com/7995240/104055057-672cfd00-51ee-11eb-96ce-d0e22eb3e0cf.mp4

I hope I could answer your question. 
PanelDueFirmware-5.0i-7.0i.zip -> being the wrong file for my board, makes a color shift to blue. heatbed color issue is there.
PanelDueFirmware-v3-5.0.zip -> displays correct color, heatbed color issue is there.

**Comment by wilriker** [comment] 2021-01-08 19:36
I cannot reproduce this on a 5i and there is no code that does paint buttons in two different colors.

A couple of ideas and questions:
* What happens if your switch tabs to either Console or Setup and then back? Does this fix the rendering for this button?
* If you tap that button will this change anything?
* Can you try rotating the screen 180° in Setup and see if this happens still?
* From the color it paints I guess your heater is in fault state, correct? If not which state is it in? Does changing the state e.g. via DWC fix the rendering?
* You said you have this issue in this 3.2.7 and also in 3.2.6. This implies you had a working version before. Please state which one that was.

**Comment by dc42** [comment] 2021-01-08 20:49
There is a colour gradient displayed on the Setup page. What does it look like?

**Comment by JPluess** [comment] 2021-01-08 21:20
Hi there, 
- Release 1.24 is working correctly!
- Release 3.2 is faulty, 

- Visiting another tab and coming back shows the same dual color icon.
- Pressing the icon, makes it filled with the same color as the notification screen
![2812a62b-ebbf-4ede-a825-4f1fa4cdb122](https://user-images.githubusercontent.com/7995240/104064992-415c2400-51ff-11eb-9967-7b151124ecb0.jpeg)

-  Rotating does not help.
- Here is the color gradient:
![79eadd4f-51b5-4dd6-8ba2-b4454a878027](https://user-images.githubusercontent.com/7995240/104064327-0efdf700-51fe-11eb-9548-8687049a76d8.jpeg)

i have tested it on 3 different screens. All have the very same Issue.
The display with a 40Pin connector and a separate screen driver board V3! 

as soon as it wants to load the temp, it "breaks" something.

**Comment by JPluess** [comment] 2021-01-08 21:29
- Resetting the heater fault with M562 P0 produces this result:
![ab29991e-c01d-4cc9-8e51-8c1877c3db22](https://user-images.githubusercontent.com/7995240/104065993-f17e5c80-5200-11eb-9d08-4cfb22d73bd0.jpeg)

**Comment by tximy** [comment] 2021-01-09 03:24
Put the correct firmware for your board (C firm over V3)

**Comment by wilriker** [comment] 2021-01-09 10:13
With a heater in fault state I can reproduce the behavior. Thanks for reporting. I will investigate the issue.

**Comment by JPluess** [comment] 2021-01-09 12:43
Perfect! I am glad we found the issue.
Have a good day😀

**Comment by wilriker** [comment] 2021-01-11 09:23
This will be fixed in the next release.

**Closed by wilriker** 2021-01-11 09:23 UTC
